/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.automation.api.teste;

import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import qaops.automation.api.dominio.User;

import static io.restassured.RestAssured.when;
import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

import org.apache.http.HttpStatus;
import org.hamcrest.CoreMatchers;

public class UserTest {
	@BeforeClass
	public static void setup() {
		RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
		RestAssured.baseURI = "https://reqres.in"; 
		RestAssured.basePath = "/api";
	}
	
	
    @Test public void testListaMetaDadosDoUsuario() {
    	given().
    		param("page", 2).
        when().
        	get("/users").
        then().
        	statusCode(HttpStatus.SC_OK)
        	.body("page", is(2))
        	.body("data", is(CoreMatchers.notNullValue()));
    }
    
    @Test public void testCriarUsuarioComSucesso() {
    	User user = new User("Sergio", "eng test");
        given().
        	contentType(ContentType.JSON).
        	body(user).
    	when().
        	post("/users").
        then().
        	statusCode(HttpStatus.SC_CREATED)
        	.body("name", is("Sergio"));
    }
}
